### ISSUE TITLE
Cannot drag and drop folders or files

### ISSUE THREAD

**Issue by AbrarSL** [NickvisionApps/Tagger#354]
```(NickvisionTagger.GNOME:2): Gtk-WARNING **: 10:11:14.226: Failed to receive drop data: Could not convert data from application/vnd.portal.filetransfer to GFile```

This is what I get on the terminal when I attempt to drag a folder onto the app. I'm using the latest stable version from flathub.

There were some older issues regarding this but the problem still persists. The linked GTK issues on those old issues seem to have been resolved as well.

**Comment by fsobolev** [comment]
> There were some older issues regarding this but the problem still persists. The linked GTK issues on those old issues seem to have been resolved as well.

And as you can see [here](https://gitlab.gnome.org/GNOME/gtk/-/issues/5348) it's [portal issue](https://www.github.com/flatpak/xdg-desktop-portal/issues/911).

**Comment by AbrarSL** [comment]
Could this be reopened? The portal issue has been resolved and apps like Amberol and Celluloid now accept folders.

**Comment by nlogozzo** [comment]
> Could this be reopened? The portal issue has been resolved and apps like Amberol and Celluloid now accept folders.

The code for DnD still exists in the app. So once the flatpak runtime is updated it should just start working again so no need to reopen.

**Comment by AbrarSL** [comment]
Those other apps use the same or older runtime though. Also from what I can tell Tagger doesn't have a drop target?

![Screenshot from 2023-11-26 17-52-16](https://github.com/NickvisionApps/Tagger/assets/69783006/581fc507-3bab-4eba-b5b5-4d952b23e3d3)

**Comment by nlogozzo** [comment]
> Those other apps use the same or older runtime though. Also from what I can tell Tagger doesn't have a drop target?


Drop target is there: https://github.com/NickvisionApps/Tagger/blob/main/NickvisionTagger.GNOME/Views/MainWindow.cs#L561

What happens when you drag in a folder? Any error message from the terminal?

**Comment by AbrarSL** [comment]
It doesn't react to the drop or output any error relevant to it. The only thing printed in the terminal is `(org.nickvision.tagger:2): Adwaita-WARNING **: 18:04:25.408: AdwApplicationWindow 0x562d6cc42280 does not have a minimum height, set the 'height-request' property to specify it`

**Comment by nlogozzo** [comment]
Ok i will do some more investigating...
